
classdef AskItemRequest < ros.Message
    %AskItemRequest MATLAB implementation of tm_msgs/AskItemRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/AskItemRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '119d57306382144e550df77a72a81fce' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'Item' 'WaitTime' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'item' 'wait_time' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        Item
        WaitTime
    end
    methods
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskItemRequest', 'Id');
            obj.Id = char(val);
        end
        function set.Item(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskItemRequest', 'Item');
            obj.Item = char(val);
        end
        function set.WaitTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AskItemRequest', 'WaitTime');
            obj.WaitTime = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.AskItemRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.AskItemRequest(strObj);
        end
    end
end
