
classdef SctResponse < ros.Message
    %SctResponse MATLAB implementation of tm_msgs/SctResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/SctResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '36fc752cb7af4e35e40e062d5409444d' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Id' 'Script' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'id' 'script' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Id
        Script
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'SctResponse', 'Header')
            obj.Header = val;
        end
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SctResponse', 'Id');
            obj.Id = char(val);
        end
        function set.Script(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SctResponse', 'Script');
            obj.Script = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.SctResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.SctResponse(strObj);
        end
    end
end
