
classdef SendScriptRequest < ros.Message
    %SendScriptRequest MATLAB implementation of tm_msgs/SendScriptRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/SendScriptRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '5dd928d0ec2b0559a4b55f04df74eb17' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'Script' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'script' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        Script
    end
    methods
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SendScriptRequest', 'Id');
            obj.Id = char(val);
        end
        function set.Script(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'SendScriptRequest', 'Script');
            obj.Script = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.SendScriptRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.SendScriptRequest(strObj);
        end
    end
end
