
classdef SetIORequest < ros.Message
    %SetIORequest MATLAB implementation of tm_msgs/SetIORequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/SetIORequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'f68a6af36df29cd75eb72b95a963915a' % The MD5 Checksum of the message definition
        PropertyList = { 'Module' 'Type' 'Pin' 'State' } % List of non-constant message properties
        ROSPropertyList = { 'module' 'type' 'pin' 'state' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
        MODULECONTROLBOX = int8(0)
        MODULEENDEFFECTOR = int8(1)
        TYPEDIGITALIN = int8(0)
        TYPEDIGITALOUT = int8(1)
        TYPEINSTANTDO = int8(2)
        TYPEANALOGIN = int8(3)
        TYPEANALOGOUT = int8(4)
        TYPEINSTANTAO = int8(5)
        STATEOFF = int8(0)
        STATEON = int8(1)
    end
    properties
        Module
        Type
        Pin
        State
    end
    methods
        function set.Module(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetIORequest', 'Module');
            obj.Module = int8(val);
        end
        function set.Type(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetIORequest', 'Type');
            obj.Type = int8(val);
        end
        function set.Pin(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetIORequest', 'Pin');
            obj.Pin = int8(val);
        end
        function set.State(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'SetIORequest', 'State');
            obj.State = single(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.SetIORequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.SetIORequest(strObj);
        end
    end
end
