
classdef AskItemResponse < ros.Message
    %AskItemResponse MATLAB implementation of tm_msgs/AskItemResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/AskItemResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '79f96d7d925273cc7a9e664679391312' % The MD5 Checksum of the message definition
        PropertyList = { 'Ok' 'Id' 'Value' } % List of non-constant message properties
        ROSPropertyList = { 'ok' 'id' 'value' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Ok
        Id
        Value
    end
    methods
        function set.Ok(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AskItemResponse', 'Ok');
            obj.Ok = logical(val);
        end
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskItemResponse', 'Id');
            obj.Id = char(val);
        end
        function set.Value(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskItemResponse', 'Value');
            obj.Value = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.AskItemResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.AskItemResponse(strObj);
        end
    end
end
