
classdef AskStaRequest < ros.Message
    %AskStaRequest MATLAB implementation of tm_msgs/AskStaRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/AskStaRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'b4d332df23aae69bb9755f2fba3f4522' % The MD5 Checksum of the message definition
        PropertyList = { 'Subcmd' 'Subdata' 'WaitTime' } % List of non-constant message properties
        ROSPropertyList = { 'subcmd' 'subdata' 'wait_time' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Subcmd
        Subdata
        WaitTime
    end
    methods
        function set.Subcmd(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskStaRequest', 'Subcmd');
            obj.Subcmd = char(val);
        end
        function set.Subdata(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskStaRequest', 'Subdata');
            obj.Subdata = char(val);
        end
        function set.WaitTime(obj, val)
            validClasses = {'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AskStaRequest', 'WaitTime');
            obj.WaitTime = double(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.AskStaRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.AskStaRequest(strObj);
        end
    end
end
