
classdef AskStaResponse < ros.Message
    %AskStaResponse MATLAB implementation of tm_msgs/AskStaResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/AskStaResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '25873f3325181d973b805ca6d8ce5c70' % The MD5 Checksum of the message definition
        PropertyList = { 'Ok' 'Subcmd' 'Subdata' } % List of non-constant message properties
        ROSPropertyList = { 'ok' 'subcmd' 'subdata' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Ok
        Subcmd
        Subdata
    end
    methods
        function set.Ok(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'AskStaResponse', 'Ok');
            obj.Ok = logical(val);
        end
        function set.Subcmd(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskStaResponse', 'Subcmd');
            obj.Subcmd = char(val);
        end
        function set.Subdata(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'AskStaResponse', 'Subdata');
            obj.Subdata = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.AskStaResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.AskStaResponse(strObj);
        end
    end
end
