
classdef CartesianMoveRequest < ros.Message
    %CartesianMoveRequest MATLAB implementation of tm_msgs/CartesianMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/CartesianMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '46373f83afb6c46513d3d786edd59f39' % The MD5 Checksum of the message definition
        PropertyList = { 'PoseTarget' } % List of non-constant message properties
        ROSPropertyList = { 'poseTarget' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.geometry_msgs.Pose' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        PoseTarget
    end
    methods
        function set.PoseTarget(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.geometry_msgs.Pose'};
            validateattributes(val, validClasses, validAttributes, 'CartesianMoveRequest', 'PoseTarget')
            obj.PoseTarget = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.CartesianMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.CartesianMoveRequest(strObj);
        end
    end
end
