
classdef JointMoveResponse < ros.Message
    %JointMoveResponse MATLAB implementation of tm_msgs/JointMoveResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/JointMoveResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '497312386196714e5f4a62411b9bd684' % The MD5 Checksum of the message definition
        PropertyList = { 'IsOK' } % List of non-constant message properties
        ROSPropertyList = { 'isOK' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        IsOK
    end
    methods
        function set.IsOK(obj, val)
            validClasses = {'logical', 'numeric'};
            validAttributes = {'nonempty', 'scalar'};
            validateattributes(val, validClasses, validAttributes, 'JointMoveResponse', 'IsOK');
            obj.IsOK = logical(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.JointMoveResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.JointMoveResponse(strObj);
        end
    end
end
