
classdef JointMoveRequest < ros.Message
    %JointMoveRequest MATLAB implementation of tm_msgs/JointMoveRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/JointMoveRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'cdca231acb928c832450acedf16ebc56' % The MD5 Checksum of the message definition
        PropertyList = { 'JointTarget' } % List of non-constant message properties
        ROSPropertyList = { 'jointTarget' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.sensor_msgs.JointState' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        JointTarget
    end
    methods
        function set.JointTarget(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.sensor_msgs.JointState'};
            validateattributes(val, validClasses, validAttributes, 'JointMoveRequest', 'JointTarget')
            obj.JointTarget = val;
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.JointMoveRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.JointMoveRequest(strObj);
        end
    end
end
