
classdef StaResponse < ros.Message
    %StaResponse MATLAB implementation of tm_msgs/StaResponse
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/StaResponse' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = '3a5171002fa543efe0e7302c1efd2051' % The MD5 Checksum of the message definition
        PropertyList = { 'Header' 'Subcmd' 'Subdata' } % List of non-constant message properties
        ROSPropertyList = { 'header' 'subcmd' 'subdata' } % List of non-constant ROS message properties
        PropertyMessageTypes = { 'ros.msggen.std_msgs.Header' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Header
        Subcmd
        Subdata
    end
    methods
        function set.Header(obj, val)
            validAttributes = {'nonempty', 'scalar'};
            validClasses = {'ros.msggen.std_msgs.Header'};
            validateattributes(val, validClasses, validAttributes, 'StaResponse', 'Header')
            obj.Header = val;
        end
        function set.Subcmd(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'StaResponse', 'Subcmd');
            obj.Subcmd = char(val);
        end
        function set.Subdata(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'StaResponse', 'Subdata');
            obj.Subdata = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.StaResponse.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.StaResponse(strObj);
        end
    end
end
