
classdef WriteItemRequest < ros.Message
    %WriteItemRequest MATLAB implementation of tm_msgs/WriteItemRequest
    %   This class was automatically generated by
    %   ros.internal.pubsubEmitter.
    %   Copyright 2014-2020 The MathWorks, Inc.
    properties (Constant)
        MessageType = 'tm_msgs/WriteItemRequest' % The ROS message type
    end
    properties (Constant, Hidden)
        MD5Checksum = 'd2adb38a608c2c354ee61bc1cbad3341' % The MD5 Checksum of the message definition
        PropertyList = { 'Id' 'Item' 'Value' } % List of non-constant message properties
        ROSPropertyList = { 'id' 'item' 'value' } % List of non-constant ROS message properties
        PropertyMessageTypes = { '' ...
            '' ...
            '' ...
            } % Types of contained nested messages
    end
    properties (Constant)
    end
    properties
        Id
        Item
        Value
    end
    methods
        function set.Id(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'WriteItemRequest', 'Id');
            obj.Id = char(val);
        end
        function set.Item(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'WriteItemRequest', 'Item');
            obj.Item = char(val);
        end
        function set.Value(obj, val)
            val = convertStringsToChars(val);
            validClasses = {'char', 'string'};
            validAttributes = {};
            validateattributes(val, validClasses, validAttributes, 'WriteItemRequest', 'Value');
            obj.Value = char(val);
        end
    end
    methods (Static, Access = {?matlab.unittest.TestCase, ?ros.Message})
        function obj = loadobj(strObj)
        %loadobj Implements loading of message from MAT file
        % Return an empty object array if the structure element is not defined
            if isempty(strObj)
                obj = ros.msggen.tm_msgs.WriteItemRequest.empty(0,1);
                return
            end
            % Create an empty message object
            obj = ros.msggen.tm_msgs.WriteItemRequest(strObj);
        end
    end
end
